// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_map_1__level_20 = "CgkIqqKPyKgOEAIQFA"; // <GPGSID>
        public const string leaderboard_map_1__level_10 = "CgkIqqKPyKgOEAIQCg"; // <GPGSID>
        public const string leaderboard_map_1__level_11 = "CgkIqqKPyKgOEAIQCw"; // <GPGSID>
        public const string leaderboard_map_1__level_1 = "CgkIqqKPyKgOEAIQAQ"; // <GPGSID>
        public const string leaderboard_map_1__level_2 = "CgkIqqKPyKgOEAIQAg"; // <GPGSID>
        public const string leaderboard_map_1__level_3 = "CgkIqqKPyKgOEAIQAw"; // <GPGSID>
        public const string leaderboard_map_1__level_4 = "CgkIqqKPyKgOEAIQBA"; // <GPGSID>
        public const string leaderboard_map_1__level_5 = "CgkIqqKPyKgOEAIQBQ"; // <GPGSID>
        public const string leaderboard_map_1__level_6 = "CgkIqqKPyKgOEAIQBg"; // <GPGSID>
        public const string leaderboard_map_1__level_7 = "CgkIqqKPyKgOEAIQBw"; // <GPGSID>
        public const string leaderboard_map_1__level_8 = "CgkIqqKPyKgOEAIQCA"; // <GPGSID>
        public const string leaderboard_map_1__level_9 = "CgkIqqKPyKgOEAIQCQ"; // <GPGSID>
        public const string leaderboard_map_1__level_16 = "CgkIqqKPyKgOEAIQEA"; // <GPGSID>
        public const string leaderboard_map_1__level_12 = "CgkIqqKPyKgOEAIQDA"; // <GPGSID>
        public const string leaderboard_map_1__level_13 = "CgkIqqKPyKgOEAIQDQ"; // <GPGSID>
        public const string leaderboard_map_1__level_14 = "CgkIqqKPyKgOEAIQDg"; // <GPGSID>
        public const string leaderboard_map_1__level_15 = "CgkIqqKPyKgOEAIQDw"; // <GPGSID>
        public const string leaderboard_map_1__level_17 = "CgkIqqKPyKgOEAIQEQ"; // <GPGSID>
        public const string leaderboard_map_1__level_18 = "CgkIqqKPyKgOEAIQEg"; // <GPGSID>
        public const string leaderboard_map_1__level_19 = "CgkIqqKPyKgOEAIQEw"; // <GPGSID>

}

